version: 2.1

jobs:
  sonarcloud_scan:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run SonarQube Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
              -Dsonar.organization=${SONAR_ORGANIZATION} \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${SONAR_TOKEN}
workflows:
  version: 2
  sonarcloud_workflow:
    jobs:
      - sonarcloud_scan
